### ISSUE TITLE
Missing license.key. Run the craft installer from your browser. 

### ISSUE THREAD

**Issue by jimzarkadas** [rsanchez/craft-cli#10]
Hey,

I added craft-cli to one of my craft projects but doesn't seem to work right. I've changed the default location of config folder and I've updated the relevant PHP constants and .craft-cli.php configs too.

When I am trying to run any of craft-cli commands I get this error:

```
[Exception]                                                      
Missing license.key. Run the craft installer from your browser.  
```

Any ideas ?

Thanks,
Jim

**Comment by rsanchez** [comment]
Which installation method did you use for craft-cli? Where is craft-cli relative to your `craft` folder. Have you re-named your `craft` folder?

This is where it expects to find your Craft license key file: https://github.com/rsanchez/craft-cli/blob/master/src/bootstrap-craft2.php#L17-L19

**Comment by jimzarkadas** [comment]
I used the global composer installation of craft-cli.

You can check the project directory in the following screenshot:

![screen shot 2016-08-24 at 15 54 09](https://cloud.githubusercontent.com/assets/1199812/17931229/0fec0828-6a13-11e6-843b-675e07d89f16.png)

Also the CRAFT_CONFIG_PATH is set correctly in public/index.php file but still doesn't work.

```
<?php

// Path to your craft/ folder
$craftPath = '../craft';

// Move plugins path to right above web root
define('CRAFT_PLUGINS_PATH', realpath(dirname(__FILE__) . "/../plugins").'/');

// Move templates path to right above web root
define('CRAFT_TEMPLATES_PATH', realpath(dirname(__FILE__) . "/../templates").'/');

// Move config path to right above web root
define('CRAFT_CONFIG_PATH', realpath(dirname(__FILE__) . "/../config").'/');

// Do not edit below this line
$path = rtrim($craftPath, '/').'/app/index.php';

if (!is_file($path))
{
    if (function_exists('http_response_code'))
    {
        http_response_code(503);
    }

    exit('Could not find your craft/ folder. Please ensure that <strong><code>$craftPath</code></strong> is set correctly in '.__FILE__);
}

require_once $path;
```

Thanks

**Comment by rsanchez** [comment]
craft-cli does not read your public/index.php file, so you'll need to add those custom paths (preferably full, absolute paths) to your .craft-cli.php: https://github.com/rsanchez/craft-cli/blob/master/sample.craft-cli.php#L33-L58

**Comment by jimzarkadas** [comment]
Yeah I 've added .craft-cli.php file but still doesn't work. I tried also adding an absolute path for config_path but it has the same behavior. Do you think that it may be related to the environment ? I use the '*' => array() to select all environments.

```
<?php

/**
 * Sample craft-cli Configuration file
 *
 * Rename this file to .craft-cli.php in your site root.
 */

// Quit if this is not being requested via the CLI
if (php_sapi_name() !== 'cli') {
    exit;
}

return array(
    /**
     * Craft path
     *
     * Specify the path to your craft folder
     * If you leave this blank, it will assume your
     * folder is <current directory>/craft
     */
    'craft_path' => __DIR__.'/craft',

    /**
     * Craft config path
     *
     * Specify the path to your craft config folder
     * If you leave this blank, it will assume your
     * folder is <current directory>/craft/config
     */
    'craft_config_path' => __DIR__.'/config',

    /**
     * Craft plugins path
     *
     * Specify the path to your craft plugins folder
     * If you leave this blank, it will assume your
     * folder is <current directory>/craft/plugins
     */
    'craft_config_path' => __DIR__.'/plugins',

    /**
     * Craft storage path
     *
     * Specify the path to your craft storage folder
     * If you leave this blank, it will assume your
     * folder is <current directory>/craft/storage
     */
    // 'craft_storage_path' => null,

    /**
     * Craft templates path
     *
     * Specify the path to your craft templates folder
     * If you leave this blank, it will assume your
     * folder is <current directory>/craft/templates
     */
    'craft_templates_path' => __DIR__.'/templates',

    /**
     * Craft translations path
     *
     * Specify the path to your craft translations folder
     * If you leave this blank, it will assume your
     * folder is <current directory>/craft/translations
     */
    // 'craft_translations_path' => null,

    /**
     * Craft environment
     *
     * The server name of your craft environment.
     */
    'environment' => null,

    /**
     * Custom commands
     *
     * An array of Command class names of
     * custom commands.
     */
    'commands' => array(
        #'\\Your\\Custom\\Command',
    ),

    /**
     * Custom command directories
     *
     * An array of directories, keyed by a namespace prefix,
     * which will be crawled for Command classes.
     */
    'commandDirs' => array(
        /*
        '\\Your\\Namespace' => '/path/to/commands',
        */
    ),
);

```

**Comment by rsanchez** [comment]
Can you update craft-cli to the latest version? It now should print some debug info if it cannot find your confit g path.

**Comment by jimzarkadas** [comment]
I updated it and still getting the same error msg. Could this be related to file permissions ? Cause it seems that it finds the path but has issues reading the file.

**Comment by rsanchez** [comment]
Can you try downloading the phar? I want to see if the global installation is the problem.

**Comment by jimzarkadas** [comment]
@rsanchez Still getting the same error. I made a fresh installation of craft through craft-cli and it works with the phar.
Although when I change the path of the config folder it breaks and throws the same error about license.key.

P.S. I work on Ubuntu if that helps somehow.

**Comment by rsanchez** [comment]
It was a missing trailing slash on the config path. I've added a fix for that.
