### ISSUE TITLE
Feature Request: craft:install flags

### ISSUE THREAD

**Issue by jordanbrauer** [rsanchez/craft-cli#14]
Hey, thanks for making this tool! I really enjoy the idea of using the command line with craft for running tests with travis-ci/gitlab-ci, and am sort of surprised that it wasn't something included with it, I digress...

There doesn't appear to be a way to install craft without the interface in the browser. An example of what I mean is similar to the way Magento does it with their [CLI tool and installation](http://devdocs.magento.com/guides/v2.0/install-gde/install/cli/install-cli-install.html),

```shell
magento setup:install \
--base-url=http://127.0.0.1/magento2/ \
--db-host=localhost \
--db-name=magento \
--db-user=magento \
--db-password=magento \
--admin-firstname=Magento \
--admin-lastname=User \
--admin-email=user@example.com \
--admin-user=admin \
--admin-password=admin123 \
--language=en_US \
--currency=USD \
--timezone=America/Chicago \
--use-rewrites=1
```

How hard would something like this be to implement? There are more flags you can pass well if you'd like more of an idea (check the link I have above to the docs page), but I doubt that's necessary haha.

**Comment by rsanchez** [comment]
We'd need to run the Craft installer logic via CLI--no small feat. I think it's a great idea, not sure if/when I'd have time to implement. I'd gladly accept a pull request.

**Comment by jordanbrauer** [comment]
@rsanchez I could look into it. Not sure if my skill level is quite there yet but I would love to help out. :)

**Comment by scrodde** [comment]
@rsanchez, @jordanbrauer I got the Craft installer to run on the CLI with a small workaround. The code is at https://github.com/scrodde/craft-cli/tree/installer

Workaround:

1. Run the `craft-cli install` cmd with the `--download-only` flag
2. Modify the `AppBehaviour::setInstalled()` function to return false in `<path>/craft/app/etc/behaviors/AppBehavior.php` (line 101)
4. Comment out line 183 `$this->download();` in src/Command/InstallCraftCommand.php
3. Run the installer again WITHOUT the `--download-only` flag

See `craft-cli -h install` for options

Do you have any ideas on how to get around this workaround?

**Comment by jordanbrauer** [comment]
@scrodde That's an interesting work around. I am going to try that today. Looking at your repository those are the exact kind of commands I am looking for.

I was talking some guys who work on Craft in the Slack channel, and they said that they are looking to maybe create a native Craft CLI later on, but not in Craft 3.

**Comment by rsanchez** [comment]
@scrodde I figured out a way to make your branch work without hacking the core. It's been added to the latest release of Craft CLI. Thanks for your contribution! There's now a separate `craft download` command. I also added an interactive mode to `craft install` so that you can run it without any command line flags and it will prompt you for input.

**Comment by scrodde** [comment]
Awesome @rsanchez!
