### ISSUE TITLE
[feature request] add phpdotenv support

### ISSUE THREAD

**Issue by tomdavies** [rsanchez/craft-cli#20]
Hey Rob,

Thanks for creating this project. Wondered if you would you be minded to accept a PR that added support for [PHP dotenv](https://github.com/vlucas/phpdotenv) to craft-cli? 

I think it's a reasonably common pattern, and  it could be easily implemented as an optional `dotenv_path` key in `.craft-cli.php`

**Comment by rsanchez** [comment]
I use dotenv pretty often myself, so I think this might be useful.

**Comment by tomdavies** [comment]
Ok sweet, I'll clean up my fork and make a PR
