### ISSUE TITLE
Option to add ssh flags for db:backup command

### ISSUE THREAD

**Issue by owldesign** [rsanchez/craft-cli#22]
Hey thanks for this plugin! I'm looking for a future request.

I use Vagrant and to backup my db I need to ssh into it, is there a way to use ssh flags for `db:backup`?

Thanks!

**Comment by rsanchez** [comment]
i think the way to handle it would be like this:

```
vagrant ssh -- 'php /vagrant/vendor/bin/craft db:backup'
```
