### ISSUE TITLE
Allow environment to be created with Composer

### ISSUE THREAD

**Issue by iduuck** [rsanchez/craft-cli#26]
When starting with `composer create-project craftcms/craft` (following this guide: https://github.com/craftcms/docs/blob/master/en/installation.md), there is no `app/Craft.php` file or folder. How to support this?

**Comment by rsanchez** [comment]
That's Craft 3. This package is Craft 2 only.

**Comment by iduuck** [comment]
Thanks for the info. Saved me some hours of brain f*ck.

Would you be interested in a Craft 3 port?

**Comment by rsanchez** [comment]
Sure, eventually. Not sure when I'll have time to port it over.
