### ISSUE TITLE
Generate command: Does this work?

### ISSUE THREAD

**Issue by csmcgee** [rsanchez/craft-cli#31]
I ran ```craft init``` and then generated a command via ```craft generate:command acme:seoclear ./commands/```.

Getting errors such as command is not defined and there are no commands defined in the "acme" namespace.

What am I missing here? I have the command in the commands directory (root of application).

.craft-cli-.php as follows
```
    'commandDirs' => array(
        /*
        '\\Your\\Namespace' => '/path/to/commands',
        */
        '\\Commands\\' => __DIR__.'/commands/',
    ),
```
Command file as follows
```
namespace Commands;

use Craft\ComponentType;
use Craft\Craft;
use ReflectionMethod;
use Symfony\Component\Console\Helper\DialogHelper;
use Symfony\Component\Console\Helper\QuestionHelper;
use Symfony\Component\Console\Input\InputOption;
use Symfony\Component\Console\Question\ChoiceQuestion;

class AcmeSeoclearCommand extends Command
{
    /**
     * {@inheritdoc}
     */
    protected $name = 'acme:seoclear';
```

Please can someone help me with this issue? Thanks.

**Comment by csmcgee** [comment]
Please note I've tried multiple configurations with no luck....

**Comment by rsanchez** [comment]
How have you installed Craft CLI? Via composer? homebrew? phar download?

I think the problem is that your command files are not autoloading (in the PHP sense). If you're using composer, you can add this to your composer.json:

```
    "autoload": {
        "psr-4": {
            "Command\\": "commands/"
        }
    }
```

**Comment by nicolasbinet** [comment]
It didn't work either for me.
I did 3 things : 

Add "commands" folder autoload "Command" namespace to composer.json

    "autoload": {
        "psr-4": {
            "Command\\": "commands/"
        }
    }


Run, composer dump-autoload -o to force autoload_classmap.php regeneration.

    composer dump-autoload -o

Add craft root vendor/autoload.php to .craft-cli.php.
Pretty sure, this should be referenced by default, or autoload and class reference will not work.

    require_once __DIR__ .  "/vendor/autoload.php";

Add "commands" folder reference to .craft-clip.php

    'commandDirs' => array(
        \\Command' => __DIR__.'/commands',
    ),

**Comment by csmcgee** [comment]
@rsanchez My apologies for not thanking you and confirming your fix worked. I had to add and dump the autoload using composer.

I would like to recommend to add some additional documentation in that area. Reading the current doc left me with the impression that it would work out of the box once I configured the `commandDirs`.

Thanks again.

**Comment by rsanchez** [comment]
As of version 0.15.0, Commands found in your `commandDirs` are autoloaded for you, if you do not already have Composer autoloading set for those directories.
