### ISSUE TITLE
PHP Fatal error when running db:restore command

### ISSUE THREAD

**Issue by alexroper** [rsanchez/craft-cli#32]
Running `craft db:backup` works fine, but when I run `craft db:restore` I get the following error.

> PHP Fatal error:  Class 'CraftCli\Command\Exception' not found in phar:///usr/local/Cellar/craft-cli/0.14.1/libexec/craft.phar/src/Command/DbRestoreCommand.php on line 78

Running Craft CLI version 0.14.1

**Comment by rsanchez** [comment]
The error from line 78 is:

```
        if (! isset($dbConfig['*'])) {
            throw new Exception('Could not find a multi-environment configuration in your db.php.');
        }
```

**Comment by alexroper** [comment]
It's true. I have no multi-environment config setup. But... why would that be a requirement?

This particular site is using Craft's default db.php format like this:
```
<?php

/**
 * Database Configuration
 *
 * All of your system's database configuration settings go in here.
 * You can see a list of the default settings in craft/app/etc/config/defaults/db.php
 */

return array(

	// The database server name or IP address. Usually this is 'localhost' or '127.0.0.1'.
	'server' => 'localhost',

	// The name of the database to select.
	'database' => '***',

	// The database username to connect with.
	'user' => '***',

	// The database password to connect with.
	'password' => '***',

	// The prefix to use when naming tables. This can be no more than 5 characters.
	'tablePrefix' => 'craft',

);
```


Also, any idea why that Exception class isn't found? I assume that's what should be echoing the 'Could not find a multi-environment configuration in your db.php.' error to the command line instead of the fatal error.

I installed with Homebrew if that helps.

**Comment by alexroper** [comment]
I can confirm that moving everything to a '*' array in `craft/config/db.php` does fix the problem.

```
return array(
  '*' => array(
    // The database server name or IP address. Usually this is 'localhost' or '127.0.0.1'.
    'server' => 'localhost',

    // The name of the database to select.
    'database' => '***',

    // The database username to connect with.
    'user' => '***',

    // The database password to connect with.
    'password' => '***',

    // The prefix to use when naming tables. This can be no more than 5 characters.
    'tablePrefix' => 'craft',
  ),
);
```

**Comment by rsanchez** [comment]
> I have no multi-environment config setup. But... why would that be a requirement?

Good point, I'll fix that.
