### ISSUE TITLE
Any chance for a version of this suitable for Craft 3 soon?

### ISSUE THREAD

**Issue by efatsi** [rsanchez/craft-cli#36]
_Really_ have enjoyed using this tool (specifically the `craft console` feature). Are there decent odds that there will be an update here to work with Craft 3?

Thanks for all the previous work here!

**Comment by efatsi** [comment]
Ah, just saw this was brought up in a previous issue - https://github.com/rsanchez/craft-cli/issues/24.

Closing this.

**Comment by rsanchez** [comment]
Since Craft 3 has its own `./craft` cli as a first-class citizen, I think the future of this project is in porting over the CLI commands to be compatible with the built-in CLI.
