### ISSUE TITLE
Won't work if you redefine directory location

### ISSUE THREAD

**Issue by Jmeyering** [rsanchez/craft-cli#5]
In our index.php directory we have these lines

```
define('CRAFT_TEMPLATES_PATH', __DIR__.'/../templates/');
define('CRAFT_CONFIG_PATH', __DIR__.'/../config/');
```

We prefer the flattened directory structure much more than the nested version. But as a result. The CLI cannot find our license.key file, because it defined its CRAFT_CONFIG_PATH as `craft/config`.

**Comment by rsanchez** [comment]
Latest version allows you to configure these paths in `.craft-cli.php`: https://github.com/rsanchez/craft-cli/blob/master/sample.craft-cli.php#L24-L67
